
import Classes.NumberFormatException;
import Classes.InvalidAgeException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Master
 */
public class InsuranceCalculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form InsuranceCalculatorUI
     */
    public InsuranceCalculatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonGetQuote = new javax.swing.JButton();
        TextBoxAgeIn = new javax.swing.JTextField();
        LabelQuoteOutput = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonClearForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Insurance Calculator");

        ButtonGetQuote.setText("Get Quote");
        ButtonGetQuote.setActionCommand("QuoteButton");
        ButtonGetQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGetQuoteActionPerformed(evt);
            }
        });

        TextBoxAgeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBoxAgeInActionPerformed(evt);
            }
        });

        LabelQuoteOutput.setText("Quote Will Appear Here");

        jLabel2.setText("Enter Your Age");

        ButtonClearForm.setText("Clear Form");
        ButtonClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextBoxAgeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(LabelQuoteOutput))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonGetQuote)
                        .addGap(116, 116, 116)
                        .addComponent(ButtonClearForm)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextBoxAgeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelQuoteOutput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonGetQuote)
                    .addComponent(ButtonClearForm))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGetQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGetQuoteActionPerformed
/*int age = Integer.parseInt(TextBoxAgeIn.getText());
double policy;*/
JFrame errorMessage = new JFrame("Insurance Calculator");

        try {
            int age = Integer.parseInt(TextBoxAgeIn.getText());
            double policy;
            
            if (isInt(age)==true){
            policy = quote(age);
            LabelQuoteOutput.setText("your policy will cost $"+policy+".");
        }
    }
        catch (InvalidAgeException ex) {
            JOptionPane.showMessageDialog(errorMessage, "Sorry, but your age prevents "+
                    "us from offering you coverage",
               "Insurance Calculator", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(errorMessage, "Invalid Input",
               "Insurance Calculator", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonGetQuoteActionPerformed

    private void TextBoxAgeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBoxAgeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBoxAgeInActionPerformed

    private void ButtonClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearFormActionPerformed
        LabelQuoteOutput.setText("Quote Will Appear Here");
        TextBoxAgeIn.setText("");
    }//GEN-LAST:event_ButtonClearFormActionPerformed
    public boolean isInt(int age) throws Exception  {
        boolean isInt = true;
        if (age != (int)age){
            isInt = false;
            throw new Exception ("Invalid Input");}
        return isInt;
        }
   
    
    
    
    public double quote(int age) throws InvalidAgeException {
    
        if (age<5 || age>110){
            throw new InvalidAgeException("Sorry, but your age prevents "+
                    "us from offering you coverage");
        }
        
        int policyQuote = (age*5)+300;
        return policyQuote;

}
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsuranceCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsuranceCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsuranceCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsuranceCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsuranceCalculatorUI().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClearForm;
    private javax.swing.JButton ButtonGetQuote;
    private javax.swing.JLabel LabelQuoteOutput;
    private javax.swing.JTextField TextBoxAgeIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
